/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: [
      "www.transparentpng.com",
      "cms.jibecdn.com",
      "www.proton.com",
      "en.higer.com",
      "valla-cranes.co.uk",
      "azwecdnepstoragewebsiteuploads.azureedge.net",
      "cms.eichertrucksandbuses.com",
      "actionaudiostore.com",
      "loweboats.com",
      "icons.iconarchive.com",
      "asia-exstatic-vivofs.vivo.com",
      "assets.newatlas.com",
      "furniturehub.pk",
      "png.pngtree.com",
      "www.pngkey.com",
      "www.emoji.co.uk",
      "www.pngall.com",
      "purepng.com",
      "www.pngall.com",
      "www.pedigree.com",
      "freepngimg.com",
      "cncatertop.com",
      "www.bosch-pt.co.in",
      "freepngimg.com",
      "www.loweboats.com",
      "images.unsplash.com",
      "toyota-indus.com",
      "upload.wikimedia.org",
      "stimg.cardekho.com",
      "cdni.autocarindia.com",
      "cdn.motor1.com",
      "www.v3cars.com",
      "imagevars.gulfnews.com",
      "www.mtctutorials.com",
      "w7.pngwing.com",
      "localhost",
      "cdn-icons-png.flaticon.com",
      "cdn.pixabay.com",
      "abelpetclinic.com",
      "cdn-images.zety.com",
      
    ],
  },
};

module.exports = nextConfig;
